runner: !DetectionRunner
  rdt_enabled: {{rdt_enabled}}
  node: !KubernetesNode
{% if owca_ssl_verify %}
    mesos_agent_endpoint: "http://127.0.0.1:5051"
{% endif %}
  action_delay: 1.
  metrics_storage: !KafkaStorage
    brokers_ips: ['{{ broker_ip }}']
    topic: "{{ owca_topic_metrics_name }}"
    max_timeout_in_seconds: 5.
  anomalies_storage: !KafkaStorage
    brokers_ips: ['{{ broker_ip }}']
    topic: "{{ owca_topic_anomalies_name }}"
    max_timeout_in_seconds: 5.
  detector: !{{owca_detector_class}}
    {% for param_name, param_value in owca_detector_params.items() %}
{{param_name}}: {{param_value}}
    {% endfor %}

  extra_labels:
    env_uniq_id: "{{env_uniq_id}}"
    own_ip: "{{own_ip}}"
